spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskgate?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Turkey
    type: com.zaxxer.hikari.HikariDataSource
    username: hbstudent
    password: hbstudent
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update